# Generated by Django 6.0 on 2026-02-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('seating', '0002_delete_seatingassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
