# Generated by Django 6.0 on 2026-02-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_delete_classroom'),
        ('departments', '0001_initial'),
        ('students', '0002_delete_student'),
        ('teachers', '0002_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
